"""Remove Agent model and make agent_id simple integer

Revision ID: 35cec93271ff
Revises: 0eac701f935c
Create Date: 2025-09-05 21:55:33.138818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35cec93271ff"
down_revision: Union[str, Sequence[str], None] = "0eac701f935c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agents_agent_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    op.create_index(op.f("ix_calls_agent_id"), "calls", ["agent_id"], unique=False)
    op.drop_constraint(op.f("calls_agent_id_fkey"), "calls", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("calls_agent_id_fkey"), "calls", "agents", ["agent_id"], ["id"]
    )
    op.drop_index(op.f("ix_calls_agent_id"), table_name="calls")
    op.create_table(
        "agents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("agents_pkey")),
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.create_index(op.f("ix_agents_agent_id"), "agents", ["agent_id"], unique=True)
    # ### end Alembic commands ###
