"""added index on start time

Revision ID: 514922d6abd5
Revises: 35cec93271ff
Create Date: 2025-09-05 23:51:34.806644

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "514922d6abd5"
down_revision: Union[str, Sequence[str], None] = "35cec93271ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calls_agent_id"), table_name="calls")
    op.create_index(op.f("ix_calls_start_time"), "calls", ["start_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calls_start_time"), table_name="calls")
    op.create_index(op.f("ix_calls_agent_id"), "calls", ["agent_id"], unique=False)
    # ### end Alembic commands ###
