"""added insights

Revision ID: 7b8664597fd5
Revises: 514922d6abd5
Create Date: 2025-09-06 01:18:32.309458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b8664597fd5"
down_revision: Union[str, Sequence[str], None] = "514922d6abd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column(
            "sentiment_scores",
            sa.JSON(),
            nullable=True,
            comment="Detailed sentiment scores for different segments",
        ),
    )
    op.add_column(
        "calls",
        sa.Column(
            "processed_at",
            sa.DateTime(),
            nullable=True,
            comment="When the call was processed for insights",
        ),
    )
    op.add_column(
        "calls",
        sa.Column(
            "processing_status",
            sa.String(length=20),
            nullable=True,
            comment="Status of insight processing: pending, processing, completed, failed",
        ),
    )
    op.alter_column(
        "calls",
        "agent_talk_ratio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Ratio of agent words to total words in the call",
        existing_nullable=True,
    )
    op.alter_column(
        "calls",
        "sentiment_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Overall sentiment score from -1 (negative) to 1 (positive)",
        existing_nullable=True,
    )
    op.alter_column(
        "calls",
        "embedding",
        existing_type=sa.TEXT(),
        comment="Sentence embeddings for the call transcript",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "calls",
        "embedding",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Sentence embeddings for the call transcript",
        existing_nullable=True,
    )
    op.alter_column(
        "calls",
        "sentiment_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Overall sentiment score from -1 (negative) to 1 (positive)",
        existing_nullable=True,
    )
    op.alter_column(
        "calls",
        "agent_talk_ratio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Ratio of agent words to total words in the call",
        existing_nullable=True,
    )
    op.drop_column("calls", "processing_status")
    op.drop_column("calls", "processed_at")
    op.drop_column("calls", "sentiment_scores")
    # ### end Alembic commands ###
